FROM nginx:latest
COPY index.html /var/www/html
COPY IMG_0356.jpeg /var/www/html
COPY IMG_0417.jpeg /var/www/html
COPY IMG_0597.jpeg /var/www/html
COPY IMG_0611.jpeg /var/www/html
COPY IMG_0617.jpeg /var/www/html