#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>

#define EEEE NULL
#define eeEE system("cat E");
#define EeeEee printf
#define eEeeEe setbuf
#define eeEee srand
#define eeEeeE time
#define eeeeeeeeeeeeeeeeeee sleep
#define eeeeeE scanf
#define eeeEE fgets
#define eEee rand
#define eeeeEE strstr
#define ee if
#define Eee else if

void EEEEEEEEE();
int EEEEEEEEEEE();

int main() {
    eEeeEe(stdout, EEEE);
    eEeeEe(stdin, EEEE);
    eEeeEe(stderr, EEEE);

	char e[128];
    EeeEee("EEEEEEEEEEEEEEEEEEEEEit's at the beginnings of ends\n");

    eeeEE(e, 120, stdin);
	ee (eeeeEE(e, "Ee")) // Checks if Ee
		EeeEee("EEEEEEEEEEEEEEEEEEEEEEEand the end of the middle.\n");
	Eee (eeeeEE(e, "EEe")) // Checks if EEe
		EeeEee("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEthe end of time and space\n");
	Eee (eeeeEE(e, "EEEEEEEEEEEEEE")) { // Checks if EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
		EeeEee("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEbut the beginning of everything");
        int EEEeeEeEeE = eeEeeE(EEEE);
        eeEee(EEEeeEeEeE); // `EEEeeEeEeE` is guaranteed to be generated by quantum fluctuations in the very fabric of timEEEeeEeEeE.
		EEEEEEEEE();
	} else
		EeeEee("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEit's at the end of nowhere and the beginning of everywhere\n");
	return 0;
}

void EEEEEEEEE() {
	EeeEee("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
	ee (!EEEEEEEEEEE())
		EeeEee("EEEEEEEEEEEEEEE\n");
	Eee (!EEEEEEEEEEE())
		EeeEee("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
	Eee (!EEEEEEEEEEE())
		EeeEee("EEEEEEEEEEEEEEEEE\n");
	Eee (!EEEEEEEEEEE())
		EeeEee("EEEEEEEEEEEEEEEEEEEEEEEE\n");
	Eee (!EEEEEEEEEEE())
		EeeEee("EEEEEEEEEEEEEEEEEEEEwhat a loser\n");
	else {
		EeeEee("NANIEEEEEEEEEEEEEEEEEEEEEEEEE\n");
		EeeEee("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n");
        eeeeeeeeeeeeeeeeeee(1);
		EeeEee("\n");
        eeeeeeeeeeeeeeeeeee(1);
		EeeEee("E\n");
        eeeeeeeeeeeeeeeeeee(1);
		EeeEee("\n");
        eeeeeeeeeeeeeeeeeee(1);
		EeeEee("EEEEEEEEEEEnjoy\n");
		eeEE
	}
}

int EEEEEEEEEEE() {
	int e = eEee();
	int eeeee;
	EeeEee("E:");
    eeeeeE("%d", &eeeee);
	return e == eeeee;
}